// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class CBGPS
{
        public const string achievement_50_point = "CgkIsL7w9pENEAIQAQ"; // <GPGSID>
        public const string achievement_100_score = "CgkIsL7w9pENEAIQAg"; // <GPGSID>
        public const string achievement_75_point = "CgkIsL7w9pENEAIQBw"; // <GPGSID>
        public const string achievement_150_score = "CgkIsL7w9pENEAIQAw"; // <GPGSID>
        public const string achievement_125__points = "CgkIsL7w9pENEAIQCA"; // <GPGSID>
        public const string achievement_sign_in = "CgkIsL7w9pENEAIQBQ"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIsL7w9pENEAIQBg"; // <GPGSID>
        public const string achievement_500_points = "CgkIsL7w9pENEAIQBA"; // <GPGSID>

}

